package Main;

import javax.swing.JOptionPane;

public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {

        initComponents();

        setLocationRelativeTo(null);
        setSize(1365, 767);
        setResizable(false);
        
        Loading.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loading = new javax.swing.JProgressBar();
        lblLoading6 = new javax.swing.JLabel();
        lblLoading4 = new javax.swing.JLabel();
        lblLoading5 = new javax.swing.JLabel();
        lblLoading3 = new javax.swing.JLabel();
        lblLoading2 = new javax.swing.JLabel();
        lblLoading1 = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1365, 757));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 190, 10));

        lblLoading6.setFont(new java.awt.Font("SF Pixelate", 0, 14)); // NOI18N
        lblLoading6.setForeground(new java.awt.Color(112, 62, 70));
        lblLoading6.setText("Ingresando al velo...");
        getContentPane().add(lblLoading6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 200, 20));

        lblLoading4.setFont(new java.awt.Font("SF Pixelate", 0, 16)); // NOI18N
        lblLoading4.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading4.setText("   ");
        getContentPane().add(lblLoading4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 200, 20));

        lblLoading5.setFont(new java.awt.Font("SF Pixelate", 0, 16)); // NOI18N
        lblLoading5.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading5.setText("   ");
        getContentPane().add(lblLoading5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 200, 20));

        lblLoading3.setFont(new java.awt.Font("SF Pixelate", 0, 16)); // NOI18N
        lblLoading3.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading3.setText("   ");
        getContentPane().add(lblLoading3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 200, 20));

        lblLoading2.setFont(new java.awt.Font("SF Pixelate", 0, 16)); // NOI18N
        lblLoading2.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading2.setText("   ");
        getContentPane().add(lblLoading2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 200, 20));

        lblLoading1.setFont(new java.awt.Font("SF Pixelate", 0, 16)); // NOI18N
        lblLoading1.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading1.setText("   ");
        getContentPane().add(lblLoading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 200, 20));

        lblLoading.setFont(new java.awt.Font("SF Pixelate", 0, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(84, 124, 118));
        lblLoading.setText("   ");
        getContentPane().add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 200, 20));

        jLabel1.setFont(new java.awt.Font("SF Pixelate", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 124, 118));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/backup-1750475593.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1365, 767));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 767));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new SplashScreen().mostrar();
    }

    public void mostrar() {
        SplashScreen s1 = new SplashScreen();
        s1.setVisible(true);

        try {
            for (int i = 0; i < 100; i++) {
                Thread.sleep(100);
                s1.Loading.setToolTipText(i + "%");

                if (i == 0) {
                    s1.lblLoading.setText(" ");
                    s1.lblLoading1.setText("Tu presencia ha");
                    s1.lblLoading3.setText("sido notificada");
                    s1.lblLoading2.setText("a las crianturas.");
                    s1.lblLoading4.setText("Aún estás a tiempo ");
                    s1.lblLoading5.setText("de retroceder.");
                }

                if (i == 10) {
                    s1.lblLoading6.setText(" ");
                }

                if (i == 20) {
                    s1.lblLoading6.setText("Ingresando al velo...");
                }

                if (i == 25) {
                    s1.lblLoading.setText(" ");
                    s1.lblLoading1.setText("Este boleto no");
                    s1.lblLoading3.setText("garantiza retorno.");
                    s1.lblLoading2.setText("Ninguno lo hace, ");
                    s1.lblLoading4.setText("en realidad.");
                    s1.lblLoading5.setText(" ");
                }

                if (i == 30) {
                    s1.lblLoading6.setText(" ");
                }

                if (i == 40) {
                    s1.lblLoading6.setText("Ingresando al velo...");
                }

                if (i == 50) {
                    s1.lblLoading.setText(" ");
                    s1.lblLoading1.setText("No abras la puerta");
                    s1.lblLoading3.setText("si oyes que alguien");
                    s1.lblLoading2.setText("llama. Aunque use");
                    s1.lblLoading4.setText("tu nombre.");
                    s1.lblLoading5.setText(" ");
                    s1.lblLoading6.setText(" ");
                }

                if (i == 60) {
                    s1.lblLoading6.setText("Ingresando al velo...");
                }

                if (i == 70) {
                    s1.lblLoading6.setText(" ");
                }

                if (i == 75) {

                    s1.lblLoading.setText(" ");
                    s1.lblLoading1.setText("El vagón asignado");
                    s1.lblLoading3.setText("te recuerda...");
                    s1.lblLoading2.setText("pero no con afecto.");
                    s1.lblLoading4.setText("");
                    s1.lblLoading5.setText(" ");
                }

                if (i == 80) {
                    s1.lblLoading6.setText("Ingresando al velo...");
                }

                if (i == 90) {
                    s1.lblLoading6.setText(" ");
                }

                s1.Loading.setValue(i);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        s1.dispose();
        //new Juego().setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoading1;
    private javax.swing.JLabel lblLoading2;
    private javax.swing.JLabel lblLoading3;
    private javax.swing.JLabel lblLoading4;
    private javax.swing.JLabel lblLoading5;
    private javax.swing.JLabel lblLoading6;
    // End of variables declaration//GEN-END:variables

}
